//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiChiTieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dmuc
    {
        public string MaDM { get; set; }
        public string TenDM { get; set; }
    }
}
