//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiChiTieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoatdong
    {
        public int Id { get; set; }
        public string MaLoai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> Tgian { get; set; }
        public Nullable<double> Tien { get; set; }
        public string MaDM { get; set; }
    }
}
